{{- if .Values.ingress.enabled }}
{{- $apiV1 := false -}}
{{- if .Capabilities.APIVersions.Has "networking.k8s.io/v1" }}
{{- $apiV1 = true -}}
apiVersion: networking.k8s.io/v1
{{ else if .Capabilities.APIVersions.Has "networking.k8s.io/v1beta1" }}
apiVersion: networking.k8s.io/v1beta1
{{ else }}
apiVersion: extensions/v1beta1
{{ end -}}
kind: Ingress
metadata:
  name: {{ include "lmotel.fullname" . }}-grpc
  labels:
    app: {{ .Values.service.name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- if .Values.ingress.customLabels }}
  {{- with .Values.ingress.customLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    nginx.ingress.kubernetes.io/grpc-backend: "true"
  {{- if .Values.ingress.annotations }}
  {{- range $key,$value := .Values.ingress.annotations }}  
    {{ $key }}: "{{ $value }}"
  {{- end }}     
  {{- end }}
spec:
  rules:
    - host: {{.Values.ingress.host}}
      {{- with .Values.service }}
      http:
        paths:
          {{- if $apiV1 }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{.name}}
                port:
                  number: {{.ports.grpc}}
          {{- else }}
          - path: /
            backend:
              serviceName: {{.name}}
              servicePort: {{.ports.grpc}}
          {{- end }}
      {{- end }}
  tls:
    - hosts:
        - {{.Values.ingress.host}}
{{- end }}
